Update release-notes.yaml

diff --git a/.github/workflows/release-notes.yaml b/.github/workflows/release-notes.yaml
--- a/.github/workflows/release-notes.yaml
+++ b/.github/workflows/release-notes.yaml
@@ -19,11 +19,21 @@ jobs:
         run: |
           chmod +x ./.github/scripts/parse_pr_for_release_notes.sh
           chmod +x ./.github/scripts/set_release_update_type.sh
+          chmod +x ./.github/test.sh
 
       - name: Extract Release Notes Content Line by Line
         id: extract_notes
         run: |
           PR_BODY="${{ github.event.pull_request.body }}"
+
+          ME=$(./.github/scripts/test.sh)
+          if [ $? -ne 0 ]; then # Check script's exit status (0 for success, 1 for error/blank)
+            echo "ERROR: 'testing not good"
+            exit 1 # Fail the step
+          fi
+          echo "exit"
+          exit 1
+          
           # get the full release note section i.e. default and any custom notes
           START_MARKER="## release notes" # ignoring case in the string to match
           FULL_RELEASE_NOTES=$(echo "$PR_BODY" | ./.github/scripts/parse_pr_for_release_notes.sh "$START_MARKER")
