Update release-notes.yaml

diff --git a/.github/workflows/release-notes.yaml b/.github/workflows/release-notes.yaml
--- a/.github/workflows/release-notes.yaml
+++ b/.github/workflows/release-notes.yaml
@@ -31,7 +31,7 @@ jobs:
           FULL_RELEASE_NOTES=$(echo "$PR_BODY" | ./.github/scripts/parse_pr_for_release_notes.sh "$START_MARKER")
           if [ $? -ne 0 ]; then # Check script's exit status (0 for success, 1 for error/blank)
             echo "ERROR: '## Release Notes' section not found or is empty/blank. Default notes are required. (FULL_RELEASE_NOTES)"
-            echo "FULL_RELEASE_NOTES=" >> $GITHUB_OUTPUT 
+            #echo "FULL_RELEASE_NOTES=" >> $GITHUB_OUTPUT 
             exit 1 # Fail the step
           fi
           
@@ -41,7 +41,7 @@ jobs:
           DEFAULT_RELEASE_NOTES=$(echo "$PR_BODY" | ./.github/scripts/parse_pr_for_release_notes.sh "$START_MARKER" "$END_MARKER")
           if [ $? -ne 0 ]; then # Check script's exit status (0 for success, 1 for error/blank)
             echo "ERROR: '## Release Notes' section not found or is empty/blank. Default notes are required. (DEFAULT_RELEASE_NOTES)"
-            echo "DEFAULT_RELEASE_NOTES=" >> $GITHUB_OUTPUT 
+            #echo "DEFAULT_RELEASE_NOTES=" >> $GITHUB_OUTPUT 
             exit 1 # Fail the step
           fi
           
@@ -81,9 +81,18 @@ jobs:
             echo "Processing app: $app_name"
             FULL_APP_HEADING="### Release Notes for ${app_name}"
             if echo "${{ env.FULL_RELEASE_NOTES }}" | grep -qFi "$FULL_APP_HEADING"; then
-              echo "  --> VALID: Found custom release notes section for '$app_name' within the scope."
+              echo "  --> VALID: Found custom release notes section for '$app_name'"
+              # get the custom release note section i.e. default and any custom notes
+              START_MARKER="$FULL_APP_HEADING" # ignoring case in the string to match
+              END_MARKER="### Release Notes for"
+              CUSTOM_RELEASE_NOTES=$(echo "$PR_BODY" | ./.github/scripts/parse_pr_for_release_notes.sh "$START_MARKER" "$END_MARKER)
+              if [ $? -ne 0 ]; then # Check script's exit status (0 for success, 1 for error/blank)
+                echo "ERROR: '## Release Notes' section not found or is empty/blank. Custom notes for '$app_name' are required. (CUSTOM_RELEASE_NOTES)"
+                #echo "CUSTOM_RELEASE_NOTES=" >> $GITHUB_OUTPUT 
+                exit 1 # Fail the step
+              fi
             else
-              echo "  --> INVALID/NOT_FOUND: No custom release notes section found for '$app_name' within the scope."
+              echo "  --> INVALID/NOT_FOUND: No custom release notes section found for '$app_name'"
             fi
           done
           
